namespace Watchfolioo.Localization;

using System;
using System.Collections.Generic;
using System.IO;

public static class Strings
{
    private const string LangFile = "language.txt";

    public static string CurrentLanguage { get; private set; } = LoadSavedLanguage();

    private static string LoadSavedLanguage()
    {
        try
        {
            if (File.Exists(LangFile))
                return File.ReadAllText(LangFile).Trim();
        }
        catch { }
        return "uk";
    }

    public static void SetLanguage(string lang)
    {
        if (_translations.ContainsKey(lang))
        {
            CurrentLanguage = lang;
            try { File.WriteAllText(LangFile, lang); } catch { }
            LanguageChanged?.Invoke();
        }
    }

    public static event Action? LanguageChanged;

    public static string Get(string key)
    {
        if (_translations.TryGetValue(CurrentLanguage, out var lang) &&
            lang.TryGetValue(key, out var value))
            return value;
        if (_translations["uk"].TryGetValue(key, out var fallback))
            return fallback;
        return key;
    }

    private static readonly Dictionary<string, Dictionary<string, string>> _translations = new()
    {
        ["uk"] = new()
        {
            ["app_title"]        = "WATCHFOLIO",
            ["search_hint"]      = "Пошук фільмів та серіалів...",
            ["nav_home"]         = "Головна",
            ["nav_movies"]       = "Фільми",
            ["nav_series"]       = "Серіали",
            ["nav_favorites"]    = "Обране",
            ["nav_settings"]     = "Налаштування",
            ["popular_movies"]   = "Популярні фільми",
            ["popular_series"]   = "Популярні серіали",
            ["new_movies_2026"]  = "Нові фільми 2026",
            ["searching_now"]    = "Зараз шукають",
            ["new_seasons_2026"] = "Нові сезони 2026",
            ["top_action"]       = "Топ бойовики",
            ["top_comedy"]       = "Топ комедії",
            ["description"]      = "Опис",
            ["your_rating"]      = "Ваша оцінка",
            ["your_comment"]     = "Ваш коментар",
            ["save_review"]      = "Зберегти відгук",
            ["review_saved"]     = "✓ Відгук збережено!",
            ["not_rated"]        = "Ви ще не оцінили",
            ["back"]             = "← Назад",
            ["add"]              = "+ Додати",
            ["catalog"]          = "Каталог",
            ["settings_title"]   = "Налаштування",
            ["language"]         = "Мова інтерфейсу",
            ["theme"]            = "Тема оформлення",
            ["theme_dark"]       = "Зараз: Темна",
            ["theme_light"]      = "Зараз: Світла",
            ["change"]           = "Змінити",
            ["genres_title"]     = "Оберіть жанри які вас цікавлять:",
            ["no_results"]       = "Нічого не знайдено",
            ["empty_list"]       = "Список порожній",
            ["login"]            = "Увійти",
            ["register"]         = "Зареєструватися",
            ["login_hint"]       = "Логін",
            ["password_hint"]    = "Пароль",
            ["create_profile"]   = "Створити профіль",
            ["back_to_login"]    = "Назад до входу",
            ["wrong_credentials"]= "Невірний логін або пароль",
            ["login_taken"]      = "Цей логін уже зайнятий!",
            ["write_review"]     = "Напишіть свій відгук...",
            ["seasons"]          = "сезонів",
            ["no_description"]   = "Опис відсутній",
            ["loading"]          = "Завантаження...",
            ["new_movie"]        = "Новий фільм",
            ["edit_movie"]       = "Редагувати фільм",
            ["save"]             = "Зберегти",
            ["cancel"]           = "Скасувати",
            ["title_error"]      = "Введіть назву!",
            ["rating_error"]     = "Рейтинг має бути від 0 до 10!",
            ["search_results"]   = "Результати пошуку",
            ["favorites"]        = "Обране",
            ["empty_favorites"]  = "Ще нічого не додано до обраного",
            ["genre_all"]        = "Усі",
            ["genre_action"]     = "Екшн",
            ["genre_drama"]      = "Драма",
            ["genre_horror"]     = "Жахи",
            ["genre_comedy"]     = "Комедія",
            ["genre_scifi"]      = "Фантастика",
            ["genre_animation"]  = "Мультфільми",
            ["genre_thriller"]   = "Трилери",
            ["type_movie"]       = "Фільм",
            ["type_series"]      = "Серіал",
            ["welcome"]          = "Ласкаво просимо до Watchfolio!",
            ["enter_credentials"] = "Введіть свої дані для входу",
            ["create_account"]   = "Створіть новий акаунт",
            ["settings_title"]    = "Налаштування",
            ["select_genres"]     = "Оберіть жанри, які вас цікавлять:",
            ["theme_title"]       = "Тема",
            ["theme_current"]     = "Поточна: ",
            ["theme_dark"]        = "Темна",
            ["theme_light"]       = "Світла",
            ["theme_change_btn"]  = "Змінити",
            ["interface_lang"]    = "Мова інтерфейсу",
        },
        ["en"] = new()
        {
            ["app_title"]        = "WATCHFOLIO",
            ["search_hint"]      = "Search movies and series...",
            ["nav_home"]         = "Home",
            ["nav_movies"]       = "Movies",
            ["nav_series"]       = "Series",
            ["nav_favorites"]    = "Favorites",
            ["nav_settings"]     = "Settings",
            ["popular_movies"]   = "Popular Movies",
            ["popular_series"]   = "Popular Series",
            ["new_movies_2026"]  = "New Movies 2026",
            ["searching_now"]    = "Trending Now",
            ["new_seasons_2026"] = "New Seasons 2026",
            ["top_action"]       = "Top Action",
            ["top_comedy"]       = "Top Comedy",
            ["description"]      = "Description",
            ["your_rating"]      = "Your Rating",
            ["your_comment"]     = "Your Comment",
            ["save_review"]      = "Save Review",
            ["review_saved"]     = "✓ Review saved!",
            ["not_rated"]        = "Not rated yet",
            ["back"]             = "← Back",
            ["add"]              = "+ Add",
            ["catalog"]          = "Catalog",
            ["settings_title"]   = "Settings",
            ["language"]         = "Interface Language",
            ["theme"]            = "Theme",
            ["theme_dark"]       = "Current: Dark",
            ["theme_light"]      = "Current: Light",
            ["change"]           = "Change",
            ["genres_title"]     = "Select genres you are interested in:",
            ["no_results"]       = "Nothing found",
            ["empty_list"]       = "List is empty",
            ["login"]            = "Sign In",
            ["register"]         = "Register",
            ["login_hint"]       = "Login",
            ["password_hint"]    = "Password",
            ["create_profile"]   = "Create Profile",
            ["back_to_login"]    = "Back to Login",
            ["wrong_credentials"]= "Wrong login or password",
            ["login_taken"]      = "This login is already taken!",
            ["write_review"]     = "Write your review...",
            ["seasons"]          = "seasons",
            ["no_description"]   = "No description",
            ["loading"]          = "Loading...",
            ["new_movie"]        = "New Movie",
            ["edit_movie"]       = "Edit Movie",
            ["save"]             = "Save",
            ["cancel"]           = "Cancel",
            ["title_error"]      = "Enter title!",
            ["rating_error"]     = "Rating must be between 0 and 10!",
            ["search_results"]   = "Search Results",
            ["favorites"]        = "Favorites",
            ["empty_favorites"]  = "Nothing added to favorites yet",
            ["genre_all"]        = "All",
            ["genre_action"]     = "Action",
            ["genre_drama"]      = "Drama",
            ["genre_horror"]     = "Horror",
            ["genre_comedy"]     = "Comedy",
            ["genre_scifi"]      = "Sci-Fi",
            ["genre_animation"]  = "Animation",
            ["genre_thriller"]   = "Thriller",
            ["type_movie"]       = "Movie",
            ["type_series"]      = "Series",
            ["welcome"]          = "Welcome to Watchfolio!",
            ["enter_credentials"] = "Enter your credentials",
            ["create_account"]   = "Create a new account",
            ["settings_title"]    = "Settings",
            ["select_genres"]     = "Select genres you are interested in:",
            ["theme_title"]       = "Theme",
            ["theme_current"]     = "Current: ",
            ["theme_dark"]        = "Dark",
            ["theme_light"]       = "Light",
            ["theme_change_btn"]  = "Change",
            ["interface_lang"]    = "Interface Language",
        },
        ["pl"] = new()
        {
            ["app_title"]        = "WATCHFOLIO",
            ["search_hint"]      = "Szukaj filmów i seriali...",
            ["nav_home"]         = "Strona główna",
            ["nav_movies"]       = "Filmy",
            ["nav_series"]       = "Seriale",
            ["nav_favorites"]    = "Ulubione",
            ["nav_settings"]     = "Ustawienia",
            ["popular_movies"]   = "Popularne filmy",
            ["popular_series"]   = "Popularne seriale",
            ["new_movies_2026"]  = "Nowe filmy 2026",
            ["trending"]         = "Teraz popularne",
            ["new_seasons"]      = "Nowe sezony 2026",
            ["top_action"]       = "Top akcja",
            ["top_comedy"]       = "Top komedia",
            ["description"]      = "Opis",
            ["your_rating"]      = "Twoja ocena",
            ["your_comment"]     = "Twój komentarz",
            ["save_review"]      = "Zapisz recenzję",
            ["review_saved"]     = "✓ Recenzja zapisana!",
            ["not_rated"]        = "Jeszcze nie oceniono",
            ["back"]             = "← Wstecz",
            ["add"]              = "+ Dodaj",
            ["catalog"]          = "Katalog",
            ["settings_title"]   = "Ustawienia",
            ["language"]         = "Język interfejsu",
            ["theme"]            = "Motyw",
            ["theme_dark"]       = "Aktualny: Ciemny",
            ["theme_light"]      = "Aktualny: Jasny",
            ["change"]           = "Zmień",
            ["genres_title"]     = "Wybierz gatunki które cię interesują:",
            ["no_results"]       = "Nic nie znaleziono",
            ["empty_list"]       = "Lista jest pusta",
            ["login"]            = "Zaloguj się",
            ["register"]         = "Zarejestruj się",
            ["login_hint"]       = "Login",
            ["password_hint"]    = "Hasło",
            ["create_profile"]   = "Utwórz profil",
            ["back_to_login"]    = "Powrót do logowania",
            ["wrong_credentials"]= "Błędny login lub hasło",
            ["login_taken"]      = "Ten login jest już zajęty!",
            ["write_review"]     = "Napisz swoją recenzję...",
            ["seasons"]          = "sezonów",
            ["no_description"]   = "Brak opisu",
            ["loading"]          = "Ładowanie...",
            ["new_movie"]        = "Nowy film",
            ["edit_movie"]       = "Edytuj film",
            ["save"]             = "Zapisz",
            ["cancel"]           = "Anuluj",
            ["title_error"]      = "Wprowadź tytuł!",
            ["rating_error"]     = "Ocena musi być od 0 do 10!",
            ["search_results"]   = "Wyniki wyszukiwania",
            ["favorites"]        = "Ulubione",
            ["empty_favorites"]  = "Nic nie dodano do ulubionych",
            ["genre_all"]        = "Wszystkie",
            ["genre_action"]     = "Akcja",
            ["genre_drama"]      = "Dramat",
            ["genre_horror"]     = "Horror",
            ["genre_comedy"]     = "Komedia",
            ["genre_scifi"]      = "Sci-Fi",
            ["genre_animation"]  = "Animacja",
            ["genre_thriller"]   = "Thriller",
            ["type_movie"]       = "Film",
            ["type_series"]      = "Serial",
            ["welcome"]          = "Witaj w Watchfolio!",
            ["enter_credentials"] = "Wprowadź swoje dane",
            ["create_account"]   = "Utwórz nowe konto",
        },
        ["de"] = new()
        {
            ["app_title"]        = "WATCHFOLIO",
            ["search_hint"]      = "Filme und Serien suchen...",
            ["nav_home"]         = "Startseite",
            ["nav_movies"]       = "Filme",
            ["nav_series"]       = "Serien",
            ["nav_favorites"]    = "Favoriten",
            ["nav_settings"]     = "Einstellungen",
            ["popular_movies"]   = "Beliebte Filme",
            ["popular_series"]   = "Beliebte Serien",
            ["new_movies_2026"]  = "Neue Filme 2026",
            ["trending"]         = "Gerade gesucht",
            ["new_seasons"]      = "Neue Staffeln 2026",
            ["top_action"]       = "Top Action",
            ["top_comedy"]       = "Top Komödie",
            ["description"]      = "Beschreibung",
            ["your_rating"]      = "Ihre Bewertung",
            ["your_comment"]     = "Ihr Kommentar",
            ["save_review"]      = "Bewertung speichern",
            ["review_saved"]     = "✓ Bewertung gespeichert!",
            ["not_rated"]        = "Noch nicht bewertet",
            ["back"]             = "← Zurück",
            ["add"]              = "+ Hinzufügen",
            ["catalog"]          = "Katalog",
            ["settings_title"]   = "Einstellungen",
            ["language"]         = "Sprache",
            ["theme"]            = "Design",
            ["theme_dark"]       = "Aktuell: Dunkel",
            ["theme_light"]      = "Aktuell: Hell",
            ["change"]           = "Ändern",
            ["genres_title"]     = "Wählen Sie interessante Genres:",
            ["no_results"]       = "Nichts gefunden",
            ["empty_list"]       = "Liste ist leer",
            ["login"]            = "Anmelden",
            ["register"]         = "Registrieren",
            ["login_hint"]       = "Benutzername",
            ["password_hint"]    = "Passwort",
            ["create_profile"]   = "Profil erstellen",
            ["back_to_login"]    = "Zurück zur Anmeldung",
            ["wrong_credentials"]= "Falscher Benutzername oder Passwort",
            ["login_taken"]      = "Dieser Login ist bereits vergeben!",
            ["write_review"]     = "Schreiben Sie Ihre Rezension...",
            ["seasons"]          = "Staffeln",
            ["no_description"]   = "Keine Beschreibung",
            ["loading"]          = "Laden...",
            ["new_movie"]        = "Neuer Film",
            ["edit_movie"]       = "Film bearbeiten",
            ["save"]             = "Speichern",
            ["cancel"]           = "Abbrechen",
            ["title_error"]      = "Titel eingeben!",
            ["rating_error"]     = "Bewertung muss zwischen 0 und 10 liegen!",
            ["search_results"]   = "Suchergebnisse",
            ["favorites"]        = "Favoriten",
            ["empty_favorites"]  = "Noch nichts zu Favoriten hinzugefügt",
            ["genre_all"]        = "Alle",
            ["genre_action"]     = "Action",
            ["genre_drama"]      = "Drama",
            ["genre_horror"]     = "Horror",
            ["genre_comedy"]     = "Komödien",
            ["genre_scifi"]      = "Sci-Fi",
            ["genre_animation"]  = "Animation",
            ["genre_thriller"]   = "Thriller",
            ["type_movie"]       = "Film",
            ["type_series"]      = "Serie",
            ["welcome"]          = "Willkommen bei Watchfolio!",
            ["enter_credentials"] = "Geben Sie Ihre Anmeldedaten ein",
            ["create_account"]   = "Neues Konto erstellen",
        },
        ["fr"] = new()
        {
            ["app_title"]        = "WATCHFOLIO",
            ["search_hint"]      = "Rechercher films et séries...",
            ["nav_home"]         = "Accueil",
            ["nav_movies"]       = "Films",
            ["nav_series"]       = "Séries",
            ["nav_favorites"]    = "Favoris",
            ["nav_settings"]     = "Paramètres",
            ["popular_movies"]   = "Films populaires",
            ["popular_series"]   = "Séries populaires",
            ["new_movies_2026"]  = "Nouveaux films 2026",
            ["trending"]         = "Tendances",
            ["new_seasons"]      = "Nouvelles saisons 2026",
            ["top_action"]       = "Top Action",
            ["top_comedy"]       = "Top Comédie",
            ["description"]      = "Description",
            ["your_rating"]      = "Votre note",
            ["your_comment"]     = "Votre commentaire",
            ["save_review"]      = "Enregistrer l'avis",
            ["review_saved"]     = "✓ Avis enregistré!",
            ["not_rated"]        = "Pas encore noté",
            ["back"]             = "← Retour",
            ["add"]              = "+ Ajouter",
            ["catalog"]          = "Catalogue",
            ["settings_title"]   = "Paramètres",
            ["language"]         = "Langue de l'interface",
            ["theme"]            = "Thème",
            ["theme_dark"]       = "Actuel: Sombre",
            ["theme_light"]      = "Actuel: Clair",
            ["change"]           = "Changer",
            ["genres_title"]     = "Sélectionnez les genres qui vous intéressent:",
            ["no_results"]       = "Rien trouvé",
            ["empty_list"]       = "Liste vide",
            ["login"]            = "Se connecter",
            ["register"]         = "S'inscrire",
            ["login_hint"]       = "Identifiant",
            ["password_hint"]    = "Mot de passe",
            ["create_profile"]   = "Créer un profil",
            ["back_to_login"]    = "Retour à la connexion",
            ["wrong_credentials"]= "Identifiant ou mot de passe incorrect",
            ["login_taken"]      = "Cet identifiant est déjà pris!",
            ["write_review"]     = "Écrivez votre avis...",
            ["seasons"]          = "saisons",
            ["no_description"]   = "Pas de description",
            ["loading"]          = "Chargement...",
            ["new_movie"]        = "Nouveau film",
            ["edit_movie"]       = "Modifier le film",
            ["save"]             = "Enregistrer",
            ["cancel"]           = "Annuler",
            ["title_error"]      = "Entrez le titre!",
            ["rating_error"]     = "La note doit être entre 0 et 10!",
            ["search_results"]   = "Résultats de recherche",
            ["favorites"]        = "Favoris",
            ["empty_favorites"]  = "Rien ajouté aux favoris",
            ["genre_all"]        = "Tous",
            ["genre_action"]     = "Action",
            ["genre_drama"]      = "Drame",
            ["genre_horror"]     = "Horreur",
            ["genre_comedy"]     = "Comédie",
            ["genre_scifi"]      = "Sci-Fi",
            ["genre_animation"]  = "Animation",
            ["genre_thriller"]   = "Thriller",
            ["type_movie"]       = "Film",
            ["type_series"]      = "Série",
            ["welcome"]          = "Bienvenue sur Watchfolio!",
            ["enter_credentials"] = "Entrez vos identifiants",
            ["create_account"]   = "Créer un nouveau compte",
        },
        ["es"] = new()
        {
            ["app_title"]        = "WATCHFOLIO",
            ["search_hint"]      = "Buscar películas y series...",
            ["nav_home"]         = "Inicio",
            ["nav_movies"]       = "Películas",
            ["nav_series"]       = "Series",
            ["nav_favorites"]    = "Favoritos",
            ["nav_settings"]     = "Configuración",
            ["popular_movies"]   = "Películas populares",
            ["popular_series"]   = "Series populares",
            ["new_movies_2026"]  = "Nuevas películas 2026",
            ["trending"]         = "Tendencias",
            ["new_seasons"]      = "Nuevas temporadas 2026",
            ["top_action"]       = "Top Acción",
            ["top_comedy"]       = "Top Comedia",
            ["description"]      = "Descripción",
            ["your_rating"]      = "Tu valoración",
            ["your_comment"]     = "Tu comentario",
            ["save_review"]      = "Guardar reseña",
            ["review_saved"]     = "✓ Reseña guardada!",
            ["not_rated"]        = "Aún no valorado",
            ["back"]             = "← Atrás",
            ["add"]              = "+ Añadir",
            ["catalog"]          = "Catálogo",
            ["settings_title"]   = "Configuración",
            ["language"]         = "Idioma de la interfaz",
            ["theme"]            = "Tema",
            ["theme_dark"]       = "Actual: Oscuro",
            ["theme_light"]      = "Actual: Claro",
            ["change"]           = "Cambiar",
            ["genres_title"]     = "Selecciona los géneros que te interesan:",
            ["no_results"]       = "No se encontró nada",
            ["empty_list"]       = "Lista vacía",
            ["login"]            = "Iniciar sesión",
            ["register"]         = "Registrarse",
            ["login_hint"]       = "Usuario",
            ["password_hint"]    = "Contraseña",
            ["create_profile"]   = "Crear perfil",
            ["back_to_login"]    = "Volver al inicio de sesión",
            ["wrong_credentials"]= "Usuario o contraseña incorrectos",
            ["login_taken"]      = "¡Este usuario ya está en uso!",
            ["write_review"]     = "Escribe tu reseña...",
            ["seasons"]          = "temporadas",
            ["no_description"]   = "Sin descripción",
            ["loading"]          = "Cargando...",
            ["new_movie"]        = "Nueva película",
            ["edit_movie"]       = "Editar película",
            ["save"]             = "Guardar",
            ["cancel"]           = "Cancelar",
            ["title_error"]      = "¡Ingrese el título!",
            ["rating_error"]     = "¡La valoración debe estar entre 0 y 10!",
            ["search_results"]   = "Resultados de búsqueda",
            ["favorites"]        = "Favoritos",
            ["empty_favorites"]  = "Aún no se ha añadido nada a favoritos",
            ["genre_all"]        = "Todos",
            ["genre_action"]     = "Acción",
            ["genre_drama"]      = "Drama",
            ["genre_horror"]     = "Terror",
            ["genre_comedy"]     = "Comedia",
            ["genre_scifi"]      = "Ciencia ficción",
            ["genre_animation"]  = "Animación",
            ["genre_thriller"]   = "Suspense",
            ["type_movie"]       = "Película",
            ["type_series"]      = "Serie",
            ["welcome"]          = "¡Bienvenido a Watchfolio!",
            ["enter_credentials"] = "Ingresa tus credenciales",
            ["create_account"]   = "Crear nueva cuenta",
        },
    };
}